### ISSUE TITLE
falcon-node-sensor after install logs show panic error (non olm install)

### ISSUE THREAD

**Issue by dmcnaught** [CrowdStrike/falcon-operator#136]
» kubectl -n falcon-operator logs -f deploy/falcon-operator-controller-manager -c manager
I1214 20:07:52.197322       1 request.go:655] Throttling request took 1.005292364s, request: GET:https://100.64.0.1:443/apis/monitoring.coreos.com/v1alpha1?timeout=32s
2021-12-14T20:07:52.403Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2021-12-14T20:07:52.403Z	INFO	setup	starting manager
I1214 20:07:52.403618       1 leaderelection.go:243] attempting to acquire leader lease falcon-operator/70435a7a.crowdstrike.com...
2021-12-14T20:07:52.403Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
I1214 20:08:08.686119       1 leaderelection.go:253] successfully acquired lease falcon-operator/70435a7a.crowdstrike.com
2021-12-14T20:08:08.686Z	INFO	controller-runtime.manager.controller.falconnodesensor	Starting EventSource	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "source": "kind source: /, Kind="}
2021-12-14T20:08:08.686Z	INFO	controller-runtime.manager.controller.falconcontainer	Starting EventSource	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconContainer", "source": "kind source: /, Kind="}
2021-12-14T20:08:08.686Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Lease","namespace":"falcon-operator","name":"70435a7a.crowdstrike.com","uid":"3a6cca45-43ad-4f0d-90a9-3f28c5d6644b","apiVersion":"coordination.k8s.io/v1","resourceVersion":"540620776"}, "reason": "LeaderElection", "message": "falcon-operator-controller-manager-65d47fdfbb-mcqk7_0f977c63-0210-47c3-8a45-b455d872fa7b became leader"}
2021-12-14T20:08:08.686Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"ConfigMap","namespace":"falcon-operator","name":"70435a7a.crowdstrike.com","uid":"faac05d0-b82b-471c-9f6c-b19fdd5dec04","apiVersion":"v1","resourceVersion":"540620775"}, "reason": "LeaderElection", "message": "falcon-operator-controller-manager-65d47fdfbb-mcqk7_0f977c63-0210-47c3-8a45-b455d872fa7b became leader"}
2021-12-14T20:08:08.786Z	INFO	controller-runtime.manager.controller.falconnodesensor	Starting EventSource	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "source": "kind source: /, Kind="}
2021-12-14T20:08:08.787Z	INFO	controller-runtime.manager.controller.falconcontainer	Starting Controller	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconContainer"}
2021-12-14T20:08:09.091Z	INFO	controller-runtime.manager.controller.falconcontainer	Starting workers	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconContainer", "worker count": 1}
2021-12-14T20:08:09.092Z	INFO	controller-runtime.manager.controller.falconnodesensor	Starting EventSource	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "source": "kind source: /, Kind="}
2021-12-14T20:08:09.192Z	INFO	controller-runtime.manager.controller.falconnodesensor	Starting Controller	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor"}
2021-12-14T20:08:09.192Z	INFO	controller-runtime.manager.controller.falconnodesensor	Starting workers	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "worker count": 1}
2021-12-14T20:08:09.192Z	INFO	controller-runtime.manager.controller.falconnodesensor	reconciling FalconNodeSensor	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
E1214 20:08:09.193179       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x262d2e0), concrete:(*runtime._type)(0x253d3c0), asserted:(*runtime._type)(0x259b480), missingMethod:""} (interface conversion: interface {} is []interface {}, not string)
goroutine 347 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x26b4500, 0xc000a42630)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:48 +0x89
panic(0x26b4500, 0xc000a42630)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/crowdstrike/falcon-operator/pkg/common.FalconSensorConfig(0xc00004c158, 0xc000a424e0)
	/workspace/pkg/common/funcs.go:48 +0x368
github.com/crowdstrike/falcon-operator/pkg/assets/node.daemonsetConfigMap(0xc0008a8120, 0x19, 0xc0009bb480, 0x12, 0xc00004c158, 0x2a81e9d)
	/workspace/pkg/assets/node/configmap.go:29 +0x27c
github.com/crowdstrike/falcon-operator/pkg/assets/node.DaemonsetConfigMap(...)
	/workspace/pkg/assets/node/configmap.go:11
github.com/crowdstrike/falcon-operator/controllers/falcon.(*FalconNodeSensorReconciler).nodeSensorConfigmap(0xc0005e1470, 0xc0008a8120, 0x19, 0xc00004c000, 0x2e298a0, 0xc000809110, 0x19)
	/workspace/controllers/falcon/falconnodesensor_controller.go:171 +0x5c
github.com/crowdstrike/falcon-operator/controllers/falcon.(*FalconNodeSensorReconciler).handleConfigMaps(0xc0005e1470, 0x2e1b7e0, 0xc000a42390, 0xc00004c000, 0x2e298a0, 0xc000809110, 0x12, 0x2e507a0, 0xc00004c000, 0x0)
	/workspace/controllers/falcon/falconnodesensor_controller.go:147 +0x4c5
github.com/crowdstrike/falcon-operator/controllers/falcon.(*FalconNodeSensorReconciler).Reconcile(0xc0005e1470, 0x2e1b7e0, 0xc000a42390, 0xc0009bb480, 0x12, 0xc0009bb460, 0x12, 0xc000a42390, 0x40c11f, 0xc00004e000, ...)
	/workspace/controllers/falcon/falconnodesensor_controller.go:73 +0x368
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0007a4640, 0x2e1b720, 0xc000912d00, 0x27836e0, 0xc000a7c0c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0007a4640, 0x2e1b720, 0xc000912d00, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x2e1b720, 0xc000912d00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000789f50)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0008d5f50, 0x2dc8300, 0xc000a422d0, 0xc000912d01, 0xc000736000)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000789f50, 0x3b9aca00, 0x0, 0x1, 0xc000736000)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x2e1b720, 0xc000912d00, 0xc0008090a0, 0x3b9aca00, 0x0, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x2e1b720, 0xc000912d00, 0xc0008090a0, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:213 +0x45e
panic: interface conversion: interface {} is []interface {}, not string [recovered]
	panic: interface conversion: interface {} is []interface {}, not string

goroutine 347 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x26b4500, 0xc000a42630)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/crowdstrike/falcon-operator/pkg/common.FalconSensorConfig(0xc00004c158, 0xc000a424e0)
	/workspace/pkg/common/funcs.go:48 +0x368
github.com/crowdstrike/falcon-operator/pkg/assets/node.daemonsetConfigMap(0xc0008a8120, 0x19, 0xc0009bb480, 0x12, 0xc00004c158, 0x2a81e9d)
	/workspace/pkg/assets/node/configmap.go:29 +0x27c
github.com/crowdstrike/falcon-operator/pkg/assets/node.DaemonsetConfigMap(...)
	/workspace/pkg/assets/node/configmap.go:11
github.com/crowdstrike/falcon-operator/controllers/falcon.(*FalconNodeSensorReconciler).nodeSensorConfigmap(0xc0005e1470, 0xc0008a8120, 0x19, 0xc00004c000, 0x2e298a0, 0xc000809110, 0x19)
	/workspace/controllers/falcon/falconnodesensor_controller.go:171 +0x5c
github.com/crowdstrike/falcon-operator/controllers/falcon.(*FalconNodeSensorReconciler).handleConfigMaps(0xc0005e1470, 0x2e1b7e0, 0xc000a42390, 0xc00004c000, 0x2e298a0, 0xc000809110, 0x12, 0x2e507a0, 0xc00004c000, 0x0)
	/workspace/controllers/falcon/falconnodesensor_controller.go:147 +0x4c5
github.com/crowdstrike/falcon-operator/controllers/falcon.(*FalconNodeSensorReconciler).Reconcile(0xc0005e1470, 0x2e1b7e0, 0xc000a42390, 0xc0009bb480, 0x12, 0xc0009bb460, 0x12, 0xc000a42390, 0x40c11f, 0xc00004e000, ...)
	/workspace/controllers/falcon/falconnodesensor_controller.go:73 +0x368
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0007a4640, 0x2e1b720, 0xc000912d00, 0x27836e0, 0xc000a7c0c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0007a4640, 0x2e1b720, 0xc000912d00, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x2e1b720, 0xc000912d00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000789f50)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0008d5f50, 0x2dc8300, 0xc000a422d0, 0xc000912d01, 0xc000736000)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000789f50, 0x3b9aca00, 0x0, 0x1, 0xc000736000)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x2e1b720, 0xc000912d00, 0xc0008090a0, 0x3b9aca00, 0x0, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x2e1b720, 0xc000912d00, 0xc0008090a0, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.6/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:213 +0x45e

**Comment by redhatrises** [comment]
Hello and thanks for opening this issue.

1. Does `kubectl get events -n falcon-operator` show any output?
2. Did you configure anything other than CID in the CRD?
3. What Kubernetes distro and version are you running?

**Comment by dmcnaught** [comment]
1. 
``` » kubectl get events -n falcon-operator
LAST SEEN   TYPE      REASON           OBJECT                                                    MESSAGE
20s         Normal    LeaderElection   configmap/70435a7a.crowdstrike.com                        falcon-operator-controller-manager-65d47fdfbb-h52tf_23203981-9ca0-4023-aafe-3ff453c33277 became leader
20s         Normal    LeaderElection   lease/70435a7a.crowdstrike.com                            falcon-operator-controller-manager-65d47fdfbb-h52tf_23203981-9ca0-4023-aafe-3ff453c33277 became leader
1s          Normal    Pulling          pod/falcon-operator-controller-manager-65d47fdfbb-h52tf   Pulling image "quay.io/crowdstrike/falcon-operator:latest"
1s          Normal    Created          pod/falcon-operator-controller-manager-65d47fdfbb-h52tf   Created container manager
1s          Normal    Started          pod/falcon-operator-controller-manager-65d47fdfbb-h52tf   Started container manager
15s         Warning   BackOff          pod/falcon-operator-controller-manager-65d47fdfbb-h52tf   Back-off restarting failed container
38s         Normal    Pulled           pod/falcon-operator-controller-manager-65d47fdfbb-h52tf   Successfully pulled image "quay.io/crowdstrike/falcon-operator:latest" in 151.017846ms
1s          Normal    Pulled           pod/falcon-operator-controller-manager-65d47fdfbb-h52tf   Successfully pulled image "quay.io/crowdstrike/falcon-operator:latest" in 143.368776ms
```

2.  
I set a tag in addition to the CID, nothing else

3.  
Kubernetes 1.21.7
kops 1.21.4 (https://github.com/kubernetes/kops) on AWS

**Comment by redhatrises** [comment]
Great. Thanks!

Does it crash when you only set the CID and not set a tag?

**Comment by dmcnaught** [comment]
Still got a panic - had a different error code:
```
E1216 00:58:45.978832       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x262d2e0), concrete:(*runtime._type)(0x253d3c0), asserted:(*runtime._type)(0x259b480), missingMethod:""} (interface conversion: interface {} is []interface {}, not string)
goroutine 346 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x26b4500, 0xc000665e90)
```

**Comment by dmcnaught** [comment]
I set the tag back to null (omiited it above) and that seems to work, no panic
```
» kubectl -n falcon-operator logs -f deploy/falcon-operator-controller-manager -c manager

I1216 01:03:59.283888       1 request.go:655] Throttling request took 1.036736598s, request: GET:https://100.64.0.1:443/apis/monitoring.coreos.com/v1alpha1?timeout=32s
2021-12-16T01:03:59.540Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2021-12-16T01:03:59.541Z	INFO	setup	starting manager
I1216 01:03:59.632565       1 leaderelection.go:243] attempting to acquire leader lease falcon-operator/70435a7a.crowdstrike.com...
2021-12-16T01:03:59.632Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
I1216 01:04:16.438009       1 leaderelection.go:253] successfully acquired lease falcon-operator/70435a7a.crowdstrike.com
2021-12-16T01:04:16.438Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Lease","namespace":"falcon-operator","name":"70435a7a.crowdstrike.com","uid":"3a6cca45-43ad-4f0d-90a9-3f28c5d6644b","apiVersion":"coordination.k8s.io/v1","resourceVersion":"541977084"}, "reason": "LeaderElection", "message": "falcon-operator-controller-manager-65d47fdfbb-h52tf_651c2c20-7373-40e3-a514-a5818bc8b134 became leader"}
2021-12-16T01:04:16.438Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"ConfigMap","namespace":"falcon-operator","name":"70435a7a.crowdstrike.com","uid":"faac05d0-b82b-471c-9f6c-b19fdd5dec04","apiVersion":"v1","resourceVersion":"541977083"}, "reason": "LeaderElection", "message": "falcon-operator-controller-manager-65d47fdfbb-h52tf_651c2c20-7373-40e3-a514-a5818bc8b134 became leader"}
2021-12-16T01:04:16.438Z	INFO	controller-runtime.manager.controller.falconcontainer	Starting EventSource	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconContainer", "source": "kind source: /, Kind="}
2021-12-16T01:04:16.438Z	INFO	controller-runtime.manager.controller.falconnodesensor	Starting EventSource	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "source": "kind source: /, Kind="}
2021-12-16T01:04:16.538Z	INFO	controller-runtime.manager.controller.falconcontainer	Starting Controller	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconContainer"}
2021-12-16T01:04:16.538Z	INFO	controller-runtime.manager.controller.falconcontainer	Starting workers	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconContainer", "worker count": 1}
2021-12-16T01:04:16.539Z	INFO	controller-runtime.manager.controller.falconnodesensor	Starting EventSource	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "source": "kind source: /, Kind="}
2021-12-16T01:04:16.740Z	INFO	controller-runtime.manager.controller.falconnodesensor	Starting EventSource	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "source": "kind source: /, Kind="}
2021-12-16T01:04:16.840Z	INFO	controller-runtime.manager.controller.falconnodesensor	Starting Controller	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor"}
2021-12-16T01:04:16.840Z	INFO	controller-runtime.manager.controller.falconnodesensor	Starting workers	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "worker count": 1}
2021-12-16T01:04:16.840Z	INFO	controller-runtime.manager.controller.falconnodesensor	reconciling FalconNodeSensor	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:16.864Z	INFO	controller-runtime.manager.controller.falconnodesensor	Creating FalconNodeSensor Configmap	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:16.864Z	INFO	controller-runtime.manager.controller.falconnodesensor	Configmap was just created. Re-queuing	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:16.864Z	INFO	controller-runtime.manager.controller.falconnodesensor	reconciling FalconNodeSensor	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:16.870Z	INFO	controller-runtime.manager.controller.falconnodesensor	Configmap was updated	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:16.896Z	INFO	controller-runtime.manager.controller.falconnodesensor	Created a new DaemonSet	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor", "DaemonSet.Namespace": "falcon-node-sensor", "DaemonSet.Name": "falcon-node-sensor"}
2021-12-16T01:04:16.896Z	INFO	controller-runtime.manager.controller.falconnodesensor	reconciling FalconNodeSensor	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:16.932Z	INFO	controller-runtime.manager.controller.falconnodesensor	Configmap was updated	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:18.532Z	INFO	controller-runtime.manager.controller.falconnodesensor	FalconNodeSensor DaemonSet configuration changed. Pods have been restarted.	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:18.532Z	INFO	controller-runtime.manager.controller.falconnodesensor	reconciling FalconNodeSensor	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:18.633Z	INFO	controller-runtime.manager.controller.falconnodesensor	Configmap was updated	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:18.732Z	INFO	controller-runtime.manager.controller.falconnodesensor	FalconNodeSensor DaemonSet configuration changed. Pods have been restarted.	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:18.733Z	INFO	controller-runtime.manager.controller.falconnodesensor	reconciling FalconNodeSensor	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:18.832Z	INFO	controller-runtime.manager.controller.falconnodesensor	Configmap was updated	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
2021-12-16T01:04:18.933Z	INFO	controller-runtime.manager.controller.falconnodesensor	FalconNodeSensor DaemonSet configuration changed. Pods have been restarted.	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "falcon-node-sensor", "DaemonSet": "falcon-node-sensor/falcon-node-sensor"}
```

**Comment by dmcnaught** [comment]
I had to set that tag as an array to create the object:
```yaml
    message_log: null
    provisioning_token: null
    tags:
      - the-tag-like-this
```

**Comment by dmcnaught** [comment]
or else:
```bash
ku apply -f falcon-node-sensor.yaml
error: error validating "falcon-node-sensor.yaml": error validating data: ValidationError(FalconNodeSensor.spec.falcon.tags): invalid type for com.crowdstrike.falcon.v1alpha1.FalconNodeSensor.spec.falcon.tags: got "string", expected "array"; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by isimluk** [comment]
Thank You @dmcnaught, I can reproduce the issues.

**Comment by dmcnaught** [comment]
I just removed the project resources from my cluster, re-downloaded the yaml files and re-added to test and it is still failing with 
```
E1216 18:58:28.449208       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x2669720), concrete:(*runtime._type)(0x2577340), asserted:(*runtime._type)(0x25d5f00), missingMethod:""} (interface conversion: interface {} is []interface {}, not string)
goroutine 329 [running]:
```

**Comment by redhatrises** [comment]
Hello @dmcnaught

The PR just contained the error handing and not the actual fix.

**Comment by dmcnaught** [comment]
@redhatrises thanks for reopening.
The error still didn't seem to be caught too - which was my surprise.

**Comment by isimluk** [comment]
@dmcnaught, Please note that the `tags` attribute has been changed in CRD
 - from array of strings
 - to comma `,` delimited string

After an upgrade to the latest image, you will have to modify your CRD from 
```
tags:
 - A
 - B
```
to
```
tags: A,B
```

Thank You!

**Comment by dmcnaught** [comment]
@isimluk falcon-node-sensor is now running in our cluster with a tag and no panic/errors, thanks for the quick turnaround on this.

**Comment by isimluk** [comment]
Thank You for confirmation, @dmcnaught!
